package com.aaread.mapper;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.aaread.model.Dianzan;
import com.aaread.model.DianzanExample;

public interface DianzanMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dianzan
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int countByExample(DianzanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dianzan
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dianzan
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int insert(Dianzan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dianzan
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int insertSelective(Dianzan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dianzan
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	List<Dianzan> selectByExample(DianzanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dianzan
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	Dianzan selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dianzan
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int updateByPrimaryKeySelective(Dianzan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dianzan
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int updateByPrimaryKey(Dianzan record);

	List<Map<String,Object>> selectZangGroup(@Param("start")Date start,@Param("end")Date end);
}