package com.aaread.mapper;

import org.apache.ibatis.annotations.Param;

import com.aaread.model.Dingyue;
import com.aaread.model.DingyueExample;
import java.util.List;

public interface DingyueMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dingyue
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int countByExample(DingyueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dingyue
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dingyue
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int insert(Dingyue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dingyue
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int insertSelective(Dingyue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dingyue
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	List<Dingyue> selectByExample(DingyueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dingyue
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	Dingyue selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dingyue
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int updateByPrimaryKeySelective(Dingyue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dingyue
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int updateByPrimaryKey(Dingyue record);

	Dingyue selectByUidTid(@Param("tid")Integer tid,@Param("uid")String uid);
}