package com.aaread.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.aaread.model.Fenzhan;
import com.aaread.model.FenzhanExample;

public interface FenzhanMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fenzhan
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int countByExample(FenzhanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fenzhan
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fenzhan
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int insert(Fenzhan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fenzhan
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int insertSelective(Fenzhan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fenzhan
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	List<Fenzhan> selectByExample(FenzhanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fenzhan
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	Fenzhan selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fenzhan
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int updateByPrimaryKeySelective(Fenzhan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fenzhan
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int updateByPrimaryKey(Fenzhan record);

	List<Fenzhan> selectList(@Param("uid")String uid,@Param("waterId")String waterId);
}