package com.aaread.mapper;

import com.aaread.model.Iorder;
import com.aaread.model.IorderExample;
import java.util.List;

public interface IorderMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iorder
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int countByExample(IorderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iorder
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iorder
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int insert(Iorder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iorder
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int insertSelective(Iorder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iorder
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	List<Iorder> selectByExample(IorderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iorder
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	Iorder selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iorder
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int updateByPrimaryKeySelective(Iorder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table iorder
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int updateByPrimaryKey(Iorder record);

	Iorder selectByOrderId(String orderid);
}