package com.aaread.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.aaread.model.Msg;
import com.aaread.model.MsgExample;

public interface MsgMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int countByExample(MsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int insert(Msg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int insertSelective(Msg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	List<Msg> selectByExample(MsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	Msg selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int updateByPrimaryKeySelective(Msg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int updateByPrimaryKey(Msg record);

	List<Msg> selectMsgList(@Param("uid")String uid);

	List<Msg> selectMsgItemList(@Param("sid")String sid);
}