package com.aaread.mapper;

import java.util.Date;

import org.apache.ibatis.annotations.Param;

import com.aaread.model.Users;
import com.aaread.model.UsersExample;
import java.util.List;

public interface UsersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int countByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int insert(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int insertSelective(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	List<Users> selectByExample(UsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	Users selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int updateByPrimaryKeySelective(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int updateByPrimaryKey(Users record);

	Users selectByUid(String uid);

	int updateBalance(@Param("uid")String uid, @Param("amount")Long amount);
	int updateArtNum(@Param("uid")String uid);

	int updateEndBalance(Users user);
	long selectYouxiaoUsersCount(@Param("end")Date end);
}