package com.aaread.mapper;

import java.util.List;

import com.aaread.model.Water;
import com.aaread.model.WaterExample;

public interface WaterMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table water
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int countByExample(WaterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table water
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table water
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int insert(Water record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table water
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int insertSelective(Water record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table water
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	List<Water> selectByExample(WaterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table water
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	Water selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table water
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int updateByPrimaryKeySelective(Water record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table water
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	int updateByPrimaryKey(Water record);

	List<Water> selectGaofeiMx(String uid);
}