package com.aaread.model;

import java.util.Date;

public class Article {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.title
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.tag
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String tag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.read_num
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Integer readNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.zan_num
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Integer zanNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.zuozhe
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String zuozhe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.pic
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String pic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.idesc
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String idesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.type
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.update_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.content
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.id
	 * @return  the value of article.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.id
	 * @param id  the value for article.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.title
	 * @return  the value of article.title
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.title
	 * @param title  the value for article.title
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.tag
	 * @return  the value of article.tag
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getTag() {
		return tag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.tag
	 * @param tag  the value for article.tag
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setTag(String tag) {
		this.tag = tag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.read_num
	 * @return  the value of article.read_num
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Integer getReadNum() {
		return readNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.read_num
	 * @param readNum  the value for article.read_num
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setReadNum(Integer readNum) {
		this.readNum = readNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.zan_num
	 * @return  the value of article.zan_num
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Integer getZanNum() {
		return zanNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.zan_num
	 * @param zanNum  the value for article.zan_num
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setZanNum(Integer zanNum) {
		this.zanNum = zanNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.zuozhe
	 * @return  the value of article.zuozhe
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getZuozhe() {
		return zuozhe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.zuozhe
	 * @param zuozhe  the value for article.zuozhe
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setZuozhe(String zuozhe) {
		this.zuozhe = zuozhe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.pic
	 * @return  the value of article.pic
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getPic() {
		return pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.pic
	 * @param pic  the value for article.pic
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setPic(String pic) {
		this.pic = pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.idesc
	 * @return  the value of article.idesc
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getIdesc() {
		return idesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.idesc
	 * @param idesc  the value for article.idesc
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setIdesc(String idesc) {
		this.idesc = idesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.type
	 * @return  the value of article.type
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.type
	 * @param type  the value for article.type
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.create_time
	 * @return  the value of article.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.create_time
	 * @param createTime  the value for article.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.update_time
	 * @return  the value of article.update_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.update_time
	 * @param updateTime  the value for article.update_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.content
	 * @return  the value of article.content
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.content
	 * @param content  the value for article.content
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}
}