package com.aaread.model;

import java.util.Date;

public class Content {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content.pic
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String pic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content.favour
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Integer favour;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content.title
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content.topic_id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long topicId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content.username
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content.update_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column content.content
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String content;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content.id
	 * @return  the value of content.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content.id
	 * @param id  the value for content.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content.uid
	 * @return  the value of content.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content.uid
	 * @param uid  the value for content.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content.pic
	 * @return  the value of content.pic
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getPic() {
		return pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content.pic
	 * @param pic  the value for content.pic
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setPic(String pic) {
		this.pic = pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content.favour
	 * @return  the value of content.favour
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Integer getFavour() {
		return favour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content.favour
	 * @param favour  the value for content.favour
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setFavour(Integer favour) {
		this.favour = favour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content.title
	 * @return  the value of content.title
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content.title
	 * @param title  the value for content.title
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content.topic_id
	 * @return  the value of content.topic_id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getTopicId() {
		return topicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content.topic_id
	 * @param topicId  the value for content.topic_id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setTopicId(Long topicId) {
		this.topicId = topicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content.username
	 * @return  the value of content.username
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content.username
	 * @param username  the value for content.username
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content.create_time
	 * @return  the value of content.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content.create_time
	 * @param createTime  the value for content.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content.update_time
	 * @return  the value of content.update_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content.update_time
	 * @param updateTime  the value for content.update_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column content.content
	 * @return  the value of content.content
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column content.content
	 * @param content  the value for content.content
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	private String topicName;
	private String userPic;
	public String getTopicName() {
		return topicName;
	}

	public void setTopicName(String topicName) {
		this.topicName = topicName;
	}

	public String getUserPic() {
		return userPic;
	}

	public void setUserPic(String userPic) {
		this.userPic = userPic;
	}
}