package com.aaread.model;

import java.util.Date;

public class Dianzan {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dianzan.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dianzan.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dianzan.c_id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long cId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dianzan.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dianzan.id
	 * @return  the value of dianzan.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dianzan.id
	 * @param id  the value for dianzan.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dianzan.uid
	 * @return  the value of dianzan.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dianzan.uid
	 * @param uid  the value for dianzan.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dianzan.c_id
	 * @return  the value of dianzan.c_id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getcId() {
		return cId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dianzan.c_id
	 * @param cId  the value for dianzan.c_id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setcId(Long cId) {
		this.cId = cId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dianzan.create_time
	 * @return  the value of dianzan.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dianzan.create_time
	 * @param createTime  the value for dianzan.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}