package com.aaread.model;

import java.util.Date;

public class Dingyue {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dingyue.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dingyue.topic_id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long topicId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dingyue.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dingyue.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dingyue.id
	 * @return  the value of dingyue.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dingyue.id
	 * @param id  the value for dingyue.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dingyue.topic_id
	 * @return  the value of dingyue.topic_id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getTopicId() {
		return topicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dingyue.topic_id
	 * @param topicId  the value for dingyue.topic_id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setTopicId(Long topicId) {
		this.topicId = topicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dingyue.uid
	 * @return  the value of dingyue.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dingyue.uid
	 * @param uid  the value for dingyue.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dingyue.create_time
	 * @return  the value of dingyue.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dingyue.create_time
	 * @param createTime  the value for dingyue.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}