package com.aaread.model;

public class Fenzhan {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fenzhan.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fenzhan.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fenzhan.c_id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long cId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fenzhan.water_id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long waterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fenzhan.amount1
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Integer amount1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fenzhan.amount2
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Integer amount2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fenzhan.num1
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Integer num1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fenzhan.num2
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Integer num2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fenzhan.total_amount
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long totalAmount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fenzhan.id
	 * @return  the value of fenzhan.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fenzhan.id
	 * @param id  the value for fenzhan.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fenzhan.uid
	 * @return  the value of fenzhan.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fenzhan.uid
	 * @param uid  the value for fenzhan.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fenzhan.c_id
	 * @return  the value of fenzhan.c_id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getcId() {
		return cId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fenzhan.c_id
	 * @param cId  the value for fenzhan.c_id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setcId(Long cId) {
		this.cId = cId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fenzhan.water_id
	 * @return  the value of fenzhan.water_id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getWaterId() {
		return waterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fenzhan.water_id
	 * @param waterId  the value for fenzhan.water_id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setWaterId(Long waterId) {
		this.waterId = waterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fenzhan.amount1
	 * @return  the value of fenzhan.amount1
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Integer getAmount1() {
		return amount1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fenzhan.amount1
	 * @param amount1  the value for fenzhan.amount1
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setAmount1(Integer amount1) {
		this.amount1 = amount1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fenzhan.amount2
	 * @return  the value of fenzhan.amount2
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Integer getAmount2() {
		return amount2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fenzhan.amount2
	 * @param amount2  the value for fenzhan.amount2
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setAmount2(Integer amount2) {
		this.amount2 = amount2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fenzhan.num1
	 * @return  the value of fenzhan.num1
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Integer getNum1() {
		return num1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fenzhan.num1
	 * @param num1  the value for fenzhan.num1
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setNum1(Integer num1) {
		this.num1 = num1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fenzhan.num2
	 * @return  the value of fenzhan.num2
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Integer getNum2() {
		return num2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fenzhan.num2
	 * @param num2  the value for fenzhan.num2
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setNum2(Integer num2) {
		this.num2 = num2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fenzhan.total_amount
	 * @return  the value of fenzhan.total_amount
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getTotalAmount() {
		return totalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fenzhan.total_amount
	 * @param totalAmount  the value for fenzhan.total_amount
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setTotalAmount(Long totalAmount) {
		this.totalAmount = totalAmount;
	}

	private Content content;

    public Content getContent() {
		return content;
	}

	public void setContent(Content content) {
		this.content = content;
	}
}