package com.aaread.model;

import java.util.Date;

public class Iorder {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iorder.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iorder.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iorder.amount
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iorder.status
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iorder.prepayId
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String prepayid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iorder.orderId
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String orderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iorder.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column iorder.update_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iorder.id
	 * @return  the value of iorder.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iorder.id
	 * @param id  the value for iorder.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iorder.uid
	 * @return  the value of iorder.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iorder.uid
	 * @param uid  the value for iorder.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iorder.amount
	 * @return  the value of iorder.amount
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iorder.amount
	 * @param amount  the value for iorder.amount
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setAmount(Long amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iorder.status
	 * @return  the value of iorder.status
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iorder.status
	 * @param status  the value for iorder.status
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iorder.prepayId
	 * @return  the value of iorder.prepayId
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getPrepayid() {
		return prepayid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iorder.prepayId
	 * @param prepayid  the value for iorder.prepayId
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setPrepayid(String prepayid) {
		this.prepayid = prepayid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iorder.orderId
	 * @return  the value of iorder.orderId
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iorder.orderId
	 * @param orderid  the value for iorder.orderId
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iorder.create_time
	 * @return  the value of iorder.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iorder.create_time
	 * @param createTime  the value for iorder.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column iorder.update_time
	 * @return  the value of iorder.update_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column iorder.update_time
	 * @param updateTime  the value for iorder.update_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}