package com.aaread.model;

import java.util.Date;

public class Msg {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msg.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msg.sender
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String sender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msg.receiver
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String receiver;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msg.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msg.status
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msg.content
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msg.sid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String sid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msg.update_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg.id
	 * @return  the value of msg.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg.id
	 * @param id  the value for msg.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg.sender
	 * @return  the value of msg.sender
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getSender() {
		return sender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg.sender
	 * @param sender  the value for msg.sender
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setSender(String sender) {
		this.sender = sender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg.receiver
	 * @return  the value of msg.receiver
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getReceiver() {
		return receiver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg.receiver
	 * @param receiver  the value for msg.receiver
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg.create_time
	 * @return  the value of msg.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg.create_time
	 * @param createTime  the value for msg.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg.status
	 * @return  the value of msg.status
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg.status
	 * @param status  the value for msg.status
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg.content
	 * @return  the value of msg.content
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg.content
	 * @param content  the value for msg.content
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg.sid
	 * @return  the value of msg.sid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg.sid
	 * @param sid  the value for msg.sid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setSid(String sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg.update_time
	 * @return  the value of msg.update_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg.update_time
	 * @param updateTime  the value for msg.update_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	private Users fuser;

	public Users getFuser() {
		return fuser;
	}

	public void setFuser(Users fuser) {
		this.fuser = fuser;
	}
}