package com.aaread.model;

public class Topic {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.name
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.gaofei_today
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long gaofeiToday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.gaofei_total
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long gaofeiTotal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.dingyue_num
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Integer dingyueNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.zimu
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String zimu;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.id
	 * @return  the value of topic.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.id
	 * @param id  the value for topic.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.name
	 * @return  the value of topic.name
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.name
	 * @param name  the value for topic.name
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.gaofei_today
	 * @return  the value of topic.gaofei_today
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getGaofeiToday() {
		return gaofeiToday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.gaofei_today
	 * @param gaofeiToday  the value for topic.gaofei_today
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setGaofeiToday(Long gaofeiToday) {
		this.gaofeiToday = gaofeiToday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.gaofei_total
	 * @return  the value of topic.gaofei_total
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getGaofeiTotal() {
		return gaofeiTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.gaofei_total
	 * @param gaofeiTotal  the value for topic.gaofei_total
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setGaofeiTotal(Long gaofeiTotal) {
		this.gaofeiTotal = gaofeiTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.dingyue_num
	 * @return  the value of topic.dingyue_num
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Integer getDingyueNum() {
		return dingyueNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.dingyue_num
	 * @param dingyueNum  the value for topic.dingyue_num
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setDingyueNum(Integer dingyueNum) {
		this.dingyueNum = dingyueNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.zimu
	 * @return  the value of topic.zimu
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getZimu() {
		return zimu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.zimu
	 * @param zimu  the value for topic.zimu
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setZimu(String zimu) {
		this.zimu = zimu;
	}
}