package com.aaread.model;

import java.util.Date;

public class Users {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.pic
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String pic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.name
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.balance
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long balance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.income
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long income;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.art_num
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Integer artNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.sex
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.position
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.end_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.update_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.id
	 * @return  the value of users.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.id
	 * @param id  the value for users.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.uid
	 * @return  the value of users.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.uid
	 * @param uid  the value for users.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.pic
	 * @return  the value of users.pic
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getPic() {
		return pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.pic
	 * @param pic  the value for users.pic
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setPic(String pic) {
		this.pic = pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.name
	 * @return  the value of users.name
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.name
	 * @param name  the value for users.name
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.balance
	 * @return  the value of users.balance
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getBalance() {
		return balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.balance
	 * @param balance  the value for users.balance
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setBalance(Long balance) {
		this.balance = balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.income
	 * @return  the value of users.income
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getIncome() {
		return income;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.income
	 * @param income  the value for users.income
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setIncome(Long income) {
		this.income = income;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.art_num
	 * @return  the value of users.art_num
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Integer getArtNum() {
		return artNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.art_num
	 * @param artNum  the value for users.art_num
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setArtNum(Integer artNum) {
		this.artNum = artNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.sex
	 * @return  the value of users.sex
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.sex
	 * @param sex  the value for users.sex
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.position
	 * @return  the value of users.position
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.position
	 * @param position  the value for users.position
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setPosition(String position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.end_time
	 * @return  the value of users.end_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.end_time
	 * @param endTime  the value for users.end_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.create_time
	 * @return  the value of users.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.create_time
	 * @param createTime  the value for users.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.update_time
	 * @return  the value of users.update_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.update_time
	 * @param updateTime  the value for users.update_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	private Long oldbalance;

	public Long getOldbalance() {
		return oldbalance;
	}

	public void setOldbalance(Long oldbalance) {
		this.oldbalance = oldbalance;
	}
}