package com.aaread.model;

import java.util.Date;

public class Water {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column water.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column water.order_id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column water.amount
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column water.balance
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Long balance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column water.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column water.type
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column water.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column water.id
	 * @return  the value of water.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column water.id
	 * @param id  the value for water.id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column water.order_id
	 * @return  the value of water.order_id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column water.order_id
	 * @param orderId  the value for water.order_id
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column water.amount
	 * @return  the value of water.amount
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column water.amount
	 * @param amount  the value for water.amount
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setAmount(Long amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column water.balance
	 * @return  the value of water.balance
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Long getBalance() {
		return balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column water.balance
	 * @param balance  the value for water.balance
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setBalance(Long balance) {
		this.balance = balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column water.uid
	 * @return  the value of water.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column water.uid
	 * @param uid  the value for water.uid
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column water.type
	 * @return  the value of water.type
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column water.type
	 * @param type  the value for water.type
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column water.create_time
	 * @return  the value of water.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column water.create_time
	 * @param createTime  the value for water.create_time
	 * @mbggenerated  Mon Jan 16 17:53:41 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}